### PR TITLE
Fix inconsistent mapping rules matching in POST requests

### LINKED ISSUE #163: Mapping rules matching for GET vs POST
Mapping rules defined in 3scale API Manager can have additional query parameters which are taken into account for mapping:
rules

For GET requests it's very straightforward – the call:
```
curl -XGET "http://localhost:8080/test?key=hello&another=parameter"
```
will match the method `get` as expected.

But for POST the behavior is a bit strange. The reason is that for "non-GET" requests the "query parameters" are [taken from the body](https://github.com/3scale/apicast/blob/v2/apicast/src/configuration.lua#L87-L89).

So, this request will not match:
```
curl -XPOST "http://localhost:8080/test?key=hello" -d "another=parameter" 
```
while this one will match the pattern `/test?key={value}` (`post` method):
```
curl -XPOST "http://localhost:8080/test" -d "key=hello&another=parameter" 
```

I am trying to understand if this is by design, or this behavior should be change.
I'd say the current behavior is not intuitive, and would only be partly useful if `application/x-www-form-urlencoded` content type is used, as it will not work for JSON payloads for example.

I believe only actual query string needs to be taken into account for mapping rules matching.

### PR DESCRIPTION
**Pull request by davidor**
Fixes #163 

Suppose we have this mapping rule: `POST /test?key={value}`.

Before this change, `curl -XPOST "http://localhost:8080/test?key=hello" -d "another=parameter"` did not match, but `curl -XPOST "http://localhost:8080/test" -d "key=hello&another=parameter"` did.

That's because in POST requests, body params were taken into account, but URI params were not. This PR changes that inconsistent behavior. Now both body & URI params are checked.

Please take a look at my comment here : https://github.com/3scale/apicast/compare/fix-mapping-rules-matching-post?expand=1#diff-5b5add30019fd642b1fd7ef108ef978eR75 and let me know if you would do it differently.

### CODE REVIEW

File: apicast/src/configuration.lua [hunk 1]
```diff
@@ -66,13 +66,16 @@ local function check_rule(req, rule, usage_t, matched_rules, params)
...
-  else
+  if method == "POST" then
     ngx.req.read_body()
-    params = ngx.req.get_post_args()
+    local body_params = ngx.req.get_post_args()
+
+    -- This will overwrite uri params if they appear in the request body. It's
+    -- an arbitrary decision. Overwriting the other way around would be equally
+    -- valid.
+    for k, v in pairs(body_params) do params[k] = v end
```
Comment (unleashed) [inline apicast/src/configuration.lua]: I'd suggest you do the reverse: iterarte `params` and overwrite `body_params[k]`  only if `body_params[k]` is nil and return the `body_params` table.

I am assuming that `POST` requests with URI parameters are not the norm (and then probably a few parameters only). IOW, I'd expect most cases to have the size of `params` smaller or way smaller than the size of `body_params`. So as is you start with a table, `body_params`, that is likely to be very similar to what you are going to return, but you are filling up another table that is likely to be empty or mostly empty. You will need `O(2*Body+Uri)` space (and potential reallocation) to fill in `params`, whereas you will need `O(2*Uri+Body)` space to fill in `body_params`. You will also need `O(Body)` lookups into `params` vs `O(Uri)` lookups in `body_params`. If the assumption `Body >> Uri` holds, it would make sense to do the reverse.

Comment (mikz) [reply apicast/src/configuration.lua]: That is a good idea @unleashed 👍

File: t/010-apicast-mapping-rules.t [hunk 2]
```diff
@@ -62,3 +62,98 @@ GET /staging/video/encode?size=100&speed=3x&user_key=foo&speed=2x
...
+  location /api/ {
+    echo "api response";
+  }
+
+  location /transactions/authrep.xml {
+    content_by_lua_block { ngx.exit(200) }
+  }
+--- request
+POST /foo?user_key=somekey
+bar=baz
```
Comment (mikz) [inline t/010-apicast-mapping-rules.t]: Might be good to test the parameter priority between uri/body.

File: apicast/src/configuration.lua (hunk 1 above)
Comment (davidor) [reply apicast/src/configuration.lua]: That's a good point @unleashed . I'll change this.

File: t/010-apicast-mapping-rules.t (hunk 2 above)
Comment (davidor) [reply t/010-apicast-mapping-rules.t]: Done.

File: apicast/src/configuration.lua (hunk 1 above)
Comment (davidor) [reply apicast/src/configuration.lua]: Changed.

File: apicast/src/configuration.lua [hunk 3]
```diff
@@ -66,16 +66,23 @@ local function check_rule(req, rule, usage_t, matched_rules, params)
...
   else
     ngx.req.read_body()
-    params = ngx.req.get_post_args()
-  end
+    local body_params = ngx.req.get_post_args()
+
+    -- Adds to body_params URI params that are not included in the body. Doing
+    -- the reverse would be more expensive, because in general, we expect the
+    -- size of body_params to be larger than the size of params.
+    for k, v in pairs(params) do
```
Comment (mikz) [inline apicast/src/configuration.lua]: This is not JITable. http://wiki.luajit.org/NYI#libraries_base-library

What about using metatable?

```lua
setmetatable(body_params, { __index = params })
```

That will just allocate one extra table, but no need for the iteration.

Comment (davidor) [reply apicast/src/configuration.lua]: :+1:
