### PR TITLE
Merge what's exposed by 'ngx_variable' in TemplateString:render()

### LINKED ISSUE #890: Liquid tag 'uri'  is not working correctly
I am using URL rewriting policy with 'value' evaluated as liquid. The value is not returned correctly. It works with liquid `{{ service.id }}`, or `{{ host }}`, but not with `{{ uri }}`.
 
**policy chain:**
```
"policy_chain": [
      {
        "name": "apicast",
        "version": "builtin",
        "configuration": {
          
        }
      },
      {
        "name": "url_rewriting",
        "version": "builtin",
        "configuration": {
          "query_args_commands": [
            {
              "op": "set",
              "arg": "arg",
              "value_type": "liquid",
              "value": "{{ uri }}"
            }
          ]
        }
      }
    ],
```
**request response:**

```
{
  "args": {
    "arg": "", 
    "user_key": "rate-limit-app-1-jsmadis-wjodncie"
  }, 
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Accept-Language": "en-US,en;q=0.9", 
    "Connection": "close", 
    "Cookie": "pl_authenticated=..."
    "Forwarded": "for=10.40.2.111;host=rate-limit-api-jsmadis-obwvarye-3scale-staging.<3scale_url>;proto=https", 
    "Host": "httpbin.org", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36", 
    "X-3Scale-Proxy-Secret-Token": "Shared_secret_sent_from_proxy_to_API_backend_78a28d5a37aa56ca", 
    "X-Forwarded-Host": "rate-limit-api-jsmadis-obwvarye-3scale-staging.<3scale_url>"
  }, 
  "origin": "10.40.2.111, 66.187.233.202", 
  "url": "https://rate-limit-api-jsmadis-obwvarye-3scale-staging.<3scale_url>/get?user_key=rate-limit-app-1-jsmadis-wjodncie&arg="
}


```

### PR DESCRIPTION
**Pull request by davidor**
Closes #890

### CODE REVIEW

File: spec/template_string_spec.lua [hunk 1]
```diff
@@ -1,6 +1,16 @@
 local TemplateString = require 'apicast.template_string'
+local ngx_variable = require 'apicast.policy.ngx_variable'
+local LinkedList = require('apicast.linked_list')
 
 describe('template string', function()
+  before_each(function()
+    -- Stub the available context to avoid depending on ngx.var.*
+    stub(ngx_variable, 'available_context', function(policies_context)
```
Comment (mikz) [inline spec/template_string_spec.lua]: Is it necessary to stub this for each test? Can't it be just one that is actually using `a_value` ?

File: spec/policy/headers/headers_spec.lua [hunk 2]
```diff
@@ -1,6 +1,12 @@
 local HeadersPolicy = require('apicast.policy.headers')
+local ngx_variable = require 'apicast.policy.ngx_variable'
 
 describe('Headers policy', function()
+  before_each(function()
+    -- avoid stubbing all the ngx.var.* and ngx.req.* in the available context
```
Comment (davidor) [inline spec/policy/headers/headers_spec.lua]: Less than ideal, but without this, all the calls to ngx.var.* and ngx.req.* will raise an "API disabled" error.

File: spec/template_string_spec.lua (hunk 1 above)
Comment (davidor) [reply spec/template_string_spec.lua]: Not needed in all the tests, just the ones that use Liquid.
Without this, all the tests that use Liquid will raise an "API disabled" error because `ngx_variable` accesses `ngx.var.*` and `ngx.req.*`.

Comment (mikz) [reply spec/template_string_spec.lua]: Sure, but each test needs this empty and only one actually needs the `a_value`.

Comment (davidor) [reply spec/template_string_spec.lua]: I've fixed this.
At first, I thought you were referring to the need for stubbing ngx_variable in general.

Comment (davidor) [reply spec/template_string_spec.lua]: Regarding the need for stubbing `ngx_variable`, I think it's a good compromise for now. I've tried exploring other solutions like injecting a function that gets the available context for Liquid in the TemplateString modules, but I didn't find any quick solution that will simplify these tests.
