### PR TITLE
Mapping Rule: Use unescaped rule

### LINKED ISSUE #1002: escaped characters in the mapping rules are not honoured
Escaped characters (such as `%20`) in the mapping rules are not honoured.

In porta, when a `%` is used in a mapping rule, it has to be part of an escape sequence to be accepted. Otherwise, porta refuses to save the settings. 

And APIcast treats the percent signs as litteral. 

This means it is not possible to use a percent in a mapping rules:
 - `/foo/100%/bar` is not accepted by porta because `%/b` is not a valid escape sequence
 - `/foo/100%25/bar` is accepted by porta but APIcast does not correctly matches it

##### Version

I'm using the hosted APIcast (SaaS).

##### Steps To Reproduce

1. Define the mapping rule `/foo/100%25/bar$`

2. Try to query the API with:

```sh
curl https://blablabla/foo/100%25/bar
curl https://blablabla/foo/100%2525/bar
```

##### Current Result

- `curl https://blablabla/foo/100%25/bar` => KO
- `curl https://blablabla/foo/100%2525/bar` => OK

##### Expected Result

- `curl https://blablabla/foo/100%25/bar` => OK
- `curl https://blablabla/foo/100%2525/bar` => KO

### PR DESCRIPTION
**Pull request by eloycoto**
This commit address the issues with the mapping rules that normalizes
the URL and mapping rules are not matching correctly.

Fix #1002
Fix THREESCALE-3468

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

File: gateway/src/apicast/proxy.lua [hunk 1]
```diff
@@ -242,7 +242,7 @@ function _M:rewrite(service, context)
     return errors.no_credentials(service)
   end
 
-  local usage, matched_rules = service:get_usage(ngx.req.get_method(), ngx.var.uri)
+  local usage, matched_rules = service:get_usage(ngx.req.get_method(), ngx.var.request_uri)
```
Comment (mayorova) [inline gateway/src/apicast/proxy.lua]: AFAIK `$request_uri` includes arguments and `$uri` doesn't.
The [docs](http://nginx.org/en/docs/http/ngx_http_core_module.html) are explicit about `$request_uri`, but not `$uri`.

So, I think the query parameters should be stripped out from `ngx.var.request_uri` first (e.g. `?q=query`).

Comment (eloycoto) [reply gateway/src/apicast/proxy.lua]: WIP PR, `ngx.var.set_uri()` modified ngx.var.uri and no request.uri, so it's not valid at all ;-)

File: gateway/src/apicast/proxy.lua [hunk 2]
```diff
@@ -242,7 +243,8 @@ function _M:rewrite(service, context)
     return errors.no_credentials(service)
   end
 
-  local usage, matched_rules = service:get_usage(ngx.req.get_method(), ngx.var.uri)
+  local target_uri = escape.escape_uri(ngx.var.uri)
```
Comment (davidor) [inline gateway/src/apicast/proxy.lua]: I think there should be a comment explaining why this is needed.
