### PR TITLE
Fix bug in export() applied to policies in the local chain

### LINKED ISSUE #672: export() does not work correctly in policies included in the local chain
Policies can define an `export` function to expose the data they need to share with other policies. 

`export` works fine for policies defined in the global chain, but it does not for policies include in a local (service level) chain. Whatever is returned in `export` does not end in `context`.

When this bug is solved, we could also solve #671 by simply using `export()` instead of `rewrite()` in the caching policy to expose the shared cache handler.

### PR DESCRIPTION
**Pull request by davidor**
Fixes #672

### CODE REVIEW

File: gateway/src/apicast/policy/local_chain/local_chain.lua [hunk 1]
```diff
@@ -45,6 +46,9 @@ local rewrite = _M.rewrite
 
 function _M:rewrite(context, ...)
   build_chain(context)
```
Comment (mikz) [inline gateway/src/apicast/policy/local_chain/local_chain.lua]: Wouldn't it be nicer if `build_chain` would return the policy_chain object? Then we would not have to call `find_policy_chain` twice.

File: gateway/src/apicast/policy/local_chain/local_chain.lua [hunk 2]
```diff
@@ -45,6 +46,9 @@ local rewrite = _M.rewrite
...
+
+  context = LinkedList.readwrite(context, find_policy_chain(context):export())
```
Comment (mikz) [inline gateway/src/apicast/policy/local_chain/local_chain.lua]: Shouldn't this  call `self:export()` instead of `find_local_policy_chain` ?

File: gateway/src/apicast/policy/local_chain/local_chain.lua (hunk 1 above)
Comment (davidor) [reply gateway/src/apicast/policy/local_chain/local_chain.lua]: You're right. It looks more readable. Changed in new commit.

File: gateway/src/apicast/policy/local_chain/local_chain.lua (hunk 2 above)
Comment (davidor) [reply gateway/src/apicast/policy/local_chain/local_chain.lua]: I don't see it. `export` is not defined in the local chain class.

Comment (mikz) [reply gateway/src/apicast/policy/local_chain/local_chain.lua]: I see. Would it make sense to add it to:
https://github.com/3scale/apicast/blob/85a14f2b5cecb199b856264df1b2e2de6b4cd9da/gateway/src/apicast/policy.lua#L11-L17

Then we should be able to just call it and it would create proper delegator.

Comment (davidor) [reply gateway/src/apicast/policy/local_chain/local_chain.lua]: I'm not sure. The case of `export` is a bit different from the rest of phases.

In the rest of phases, we just call that phase for each of the policies. `export` needs to build a list instead. Like in https://github.com/3scale/apicast/blob/869aa91a3e435cdb1f30cdc5fac698d3adba83f5/gateway/src/apicast/policy_chain.lua#L114

Comment (mikz) [reply gateway/src/apicast/policy/local_chain/local_chain.lua]: Only the PolicyChain merges those exports. The rest of policies just export something. I think that is exactly the same as the other phases. And if every policy would have an export function we could get rid of the `or`: 
https://github.com/3scale/apicast/blob/869aa91a3e435cdb1f30cdc5fac698d3adba83f5/gateway/src/apicast/policy_chain.lua#L120
Making it easier for LuaJIT.

No need to change this. I just thought it would be even nicer cleanup to treat all phases the same.

Comment (davidor) [reply gateway/src/apicast/policy/local_chain/local_chain.lua]: I'd leave this for a future PR.

**Comment by davidor** [comment]
Rebased to solve the changelog conflicts.
